"""
SIH26099 - AI-Driven Standardization & Harmonization of Material Codes Across CPSEs
Module: Canonical Material & Common National Material Code Service
Description: Manages the National Material Master (NMM Series) prototype identifiers,
             cross-enterprise CPSE code mappings, and multi-tier provenance traceability.

IMPORTANT GOVERNANCE DIRECTIVE:
These codes are labeled as "Prototype Common Material Code" (NMM = National Material Master Prototype Identifier).
They are NOT claimed to be official government material codes.
"""

import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from datetime import datetime
import json
import re
import sqlite3
from typing import Dict, List, Optional, Any

from backend.app.cpse.models import CREATE_TABLES_SQL

PROTOTYPE_DISCLAIMER = (
    "Prototype Common Material Code (NMM Series). "
    "NMM = National Material Master prototype identifier generated by the standardization engine. "
    "This is an algorithmic demonstration of cross-enterprise harmonization and is NOT an official government material code."
)

DEFAULT_PROTOTYPE_CANONICALS = [
    {
        "national_material_code": "NMM-000001",
        "canonical_code": "NMM-000001",
        "standardized_description": "Hex Head Bolt M10 x 50mm Stainless Steel SS304 Full Thread Grade 8.8",
        "category": "Fasteners & Mechanical Hardware",
        "material_type": "Standard Hardware / Consumable",
        "standard_specification": "ISO 4014 / DIN 931 / SS304 / Grade 8.8 / M10x50",
        "standard_uom": "EA",
        "technical_attributes": {
            "standard": "ISO 4014 / DIN 931",
            "material_grade": "SS304",
            "dimensions": "M10x50mm",
            "thread_type": "Full Thread",
            "tensile_rating": "Grade 8.8 High Tensile",
        },
        "approval_status": "APPROVED",
    },
    {
        "national_material_code": "NMM-000002",
        "canonical_code": "NMM-000002",
        "standardized_description": "Hex Head Bolt M10 x 50mm Marine Grade Stainless Steel SS316 Acid Resistant",
        "category": "Fasteners & Mechanical Hardware",
        "material_type": "Standard Hardware / Consumable",
        "standard_specification": "ISO 4014 / DIN 931 / SS316 / Marine Grade / M10x50",
        "standard_uom": "EA",
        "technical_attributes": {
            "standard": "ISO 4014 / DIN 931",
            "material_grade": "SS316",
            "dimensions": "M10x50mm",
            "thread_type": "Full Thread",
            "corrosion_resistance": "Marine / Acid Resistant",
        },
        "approval_status": "APPROVED",
    },
    {
        "national_material_code": "NMM-000003",
        "canonical_code": "NMM-000003",
        "standardized_description": "Seamless Carbon Steel Pipe 2 Inch NB Schedule 40 ASTM A106 Grade B",
        "category": "Piping & Tubing",
        "material_type": "Piping Component",
        "standard_specification": "ASTM A106 Grade B / ASME B36.10M / 2 Inch Sch 40 / Beveled Ends",
        "standard_uom": "MTR",
        "technical_attributes": {
            "standard": "ASTM A106 Grade B / ASME B36.10M",
            "material_grade": "A106-B Carbon Steel",
            "nominal_bore": "2 Inch (50mm NB)",
            "schedule": "Sch 40",
            "end_connection": "Beveled Ends (BE)",
        },
        "approval_status": "APPROVED",
    },
    {
        "national_material_code": "NMM-000004",
        "canonical_code": "NMM-000004",
        "standardized_description": "Flanged Ball Valve 2 Inch Class 150 WCB Body SS316 Trim",
        "category": "Valves & Actuators",
        "material_type": "Process Flow Control",
        "standard_specification": "ASME B16.34 / Class 150 / ASTM A216 WCB / SS316 (CF8M) Trim / 2 Inch",
        "standard_uom": "EA",
        "technical_attributes": {
            "standard": "ASME B16.34 / API 6D",
            "body_material": "ASTM A216 WCB Cast Carbon Steel",
            "trim_material": "SS316 / CF8M Stainless Steel",
            "pressure_class": "Class 150# Flanged",
            "size": "2 Inch Flanged",
        },
        "approval_status": "APPROVED",
    },
    {
        "national_material_code": "NMM-000005",
        "canonical_code": "NMM-000005",
        "standardized_description": "Centrifugal Pump Impeller 250mm Diameter Closed Type Stainless Steel SS316",
        "category": "Pumps & Rotating Equipment",
        "material_type": "Rotating Equipment Spare",
        "standard_specification": "Closed Impeller 250mm Dia / Dynamic Balanced / CF8M (SS316) / Boiler & Process Service",
        "standard_uom": "EA",
        "technical_attributes": {
            "equipment_type": "Centrifugal Pump Impeller",
            "diameter": "250mm Diameter",
            "impeller_type": "Enclosed / Dynamically Balanced",
            "material_grade": "CF8M / SS316 Stainless Steel",
            "application": "Boiler Feed & Process Fluid Circulation",
        },
        "approval_status": "APPROVED",
    },
    {
        "national_material_code": "NMM-000006",
        "canonical_code": "NMM-000006",
        "standardized_description": "Transformer Mineral Insulating Oil High Dielectric Voltage Grade",
        "category": "Electrical & Insulating Oils",
        "material_type": "Electrical Consumable",
        "standard_specification": "IEC 60296 / IS 335 / Breakdown Voltage >= 30kV / 12V Grade",
        "standard_uom": "LTR",
        "technical_attributes": {
            "standard": "IEC 60296 / IS 335",
            "dielectric_breakdown": ">= 30kV",
            "grade": "12V Mineral Oil",
            "application": "HV Power Transformer Insulating & Cooling",
        },
        "approval_status": "APPROVED",
    },
    {
        "national_material_code": "NMM-000007",
        "canonical_code": "NMM-000007",
        "standardized_description": "Spiral Wound Gasket 2 Inch Class 150 SS304 Inner Ring Flexible Graphite Filler",
        "category": "Seals & Gaskets",
        "material_type": "Sealing Component",
        "standard_specification": "ASME B16.20 / Class 150 / 2 Inch / SS304 Winding with Graphite",
        "standard_uom": "EA",
        "technical_attributes": {
            "standard": "ASME B16.20",
            "pressure_class": "Class 150#",
            "size": "2 Inch",
            "winding_material": "SS304 Stainless Steel",
            "filler_material": "Flexible Graphite",
        },
        "approval_status": "APPROVED",
    },
    {
        "national_material_code": "NMM-000008",
        "canonical_code": "NMM-000008",
        "standardized_description": "Carbon Steel 90 Degree Long Radius Pipe Elbow 2 Inch Schedule 40 Butt Weld",
        "category": "Piping & Tubing Fittings",
        "material_type": "Piping Fitting",
        "standard_specification": "ASME B16.9 / ASTM A234 WPB / 2 Inch Sch 40 / Long Radius 90 Deg",
        "standard_uom": "EA",
        "technical_attributes": {
            "standard": "ASME B16.9 / ASTM A234 WPB",
            "bend_angle": "90 Degree Elbow",
            "radius_type": "Long Radius (LR)",
            "dimensions": "2 Inch Schedule 40",
            "connection_type": "Butt Weld (BW)",
        },
        "approval_status": "APPROVED",
    },
]


def generate_prototype_code(index: int) -> str:
    """
    Generates a deterministic prototype code:
    e.g., index 1 -> NMM-000001
    NMM = National Material Master prototype identifier.
    """
    return f"NMM-{index:06d}"


def generate_canonical_description(source: Dict[str, Any]) -> str:
    """
    Synthesizes a standardized, professional canonical description from source material data.
    Preserves all technical tokens (dimensions, grades, specifications) without hallucinating.
    """
    raw_desc = (source.get("description") or "").strip()
    spec = (source.get("specification") or "").strip()
    grade = (source.get("material_grade") or "").strip()
    dimensions = (source.get("dimensions") or "").strip()

    # Clean redundant whitespace
    raw_desc = re.sub(r"\s+", " ", raw_desc)

    # Convert all-caps string to title-cased words while preserving technical abbreviations
    words = raw_desc.split(" ")
    formatted_words = []
    UPPERCASE_TOKENS = {
        "SS304", "SS316", "SS316L", "SS304L", "A106", "A106-B", "ASTM", "ASME",
        "DIN", "ISO", "IS", "IEC", "WCB", "CF8M", "NB", "SCH", "SCH40", "SCH80",
        "LR", "SR", "BW", "SW", "NPT", "BSP", "BSPT", "ANSI", "API", "EA", "NOS",
        "MTR", "LTR", "KG", "SET", "HV", "LV", "MV", "DC", "AC", "LED", "PVC",
        "XLPE", "FRLS", "GI", "MS", "CS", "CI", "DI", "SS", "PTFE", "EPDM", "NBR",
        "M10", "M12", "M16", "M20", "M24", "M8", "M6", "PN10", "PN16", "PN25", "PN40",
        "150#", "300#", "600#", "SQ", "MM", "MM2", "KM", "KV", "KW", "HP", "RPM"
    }

    for w in words:
        clean_w = w.rstrip(",.;:()")
        upper_w = clean_w.upper()
        punct = w[len(clean_w):] if len(w) > len(clean_w) else ""
        if upper_w in UPPERCASE_TOKENS or any(char.isdigit() for char in upper_w):
            formatted_words.append(upper_w + punct)
        elif len(upper_w) <= 2:
            formatted_words.append(upper_w + punct)
        else:
            formatted_words.append(clean_w.capitalize() + punct)

    desc_clean = " ".join(formatted_words)

    # Check if spec or grade or dimensions are already in desc
    extra_parts = []
    desc_lower = desc_clean.lower()
    if grade and grade.lower() not in desc_lower and grade.lower() != "n/a":
        extra_parts.append(grade)
    if dimensions and dimensions.lower() not in desc_lower and dimensions.lower() != "n/a":
        extra_parts.append(dimensions)
    if spec and spec.lower() not in desc_lower and spec.lower() != "n/a":
        if len(spec) < 60:
            extra_parts.append(spec)

    if extra_parts:
        return f"{desc_clean} {' '.join(extra_parts)}".strip()
    return desc_clean


def determine_canonical_category(source: Dict[str, Any]) -> str:
    """
    Determines commodity / procurement category using source attributes or keyword rules.
    Falls back to 'Unclassified' if uncertain, preventing arbitrary category fabrication.
    """
    src_cat = (source.get("category") or "").strip()
    if src_cat and src_cat.lower() not in ("unclassified", "general", "n/a", "none"):
        return src_cat

    # Keyword rules based on Indian CPSE public procurement taxonomy
    text = f"{source.get('description', '')} {source.get('specification', '')} {source.get('material_type', '')}".lower()

    if any(k in text for k in ["cable", "wire", "conductor", "armoured", "unarmoured", "core"]):
        return "Electrical & Cables"
    if any(k in text for k in ["valve", "actuator", "ball valve", "gate valve", "globe valve", "check valve"]):
        return "Valves & Actuators"
    if any(k in text for k in ["pipe", "tubing", "seamless pipe", "erw pipe"]):
        return "Piping & Tubing"
    if any(k in text for k in ["elbow", "tee", "reducer", "flange", "fitting", "nipple", "coupling"]):
        return "Piping & Tubing Fittings"
    if any(k in text for k in ["bolt", "nut", "screw", "washer", "stud", "fastener", "hex head"]):
        return "Fasteners & Mechanical Hardware"
    if any(k in text for k in ["pump", "impeller", "casing", "compressor", "turbine", "rotating"]):
        return "Pumps & Rotating Equipment"
    if any(k in text for k in ["gasket", "seal", "o-ring", "mechanical seal", "packing"]):
        return "Seals & Gaskets"
    if any(k in text for k in ["oil", "transformer oil", "lubricant", "grease", "insulating oil"]):
        return "Electrical & Insulating Oils"
    if any(k in text for k in ["bearing", "bushing", "ball bearing", "roller bearing"]):
        return "Bearings & Power Transmission"

    return "Unclassified"


class CanonicalMaterialService:
    """
    Manages the Canonical Material / Common National Material Code module.
    Features:
    - Deterministic NMM-XXXXXX code generation
    - Cross-enterprise multi-CPSE provenance aggregation
    - Full traceability tree visualization
    - Search, category, CPSE, and approval status filters
    """

    def __init__(self, db_path: Optional[Path] = None):
        self.project_root = PROJECT_ROOT
        self.db_path = db_path or (
            self.project_root / "outputs" / "analysis" / "cpse_master.db"
        )
        self.db_path.parent.mkdir(parents=True, exist_ok=True)
        self._ensure_schema_and_seed()

    def _get_connection(self) -> sqlite3.Connection:
        conn = sqlite3.connect(self.db_path)
        conn.row_factory = sqlite3.Row
        return conn

    def _ensure_schema_and_seed(self) -> None:
        """
        Migrates canonical_materials table to support the full NMM schema
        and seeds deterministic prototype codes with cross-enterprise links.
        """
        with self._get_connection() as conn:
            cur = conn.cursor()

            # Ensure all 6 base tables exist
            cur.executescript(CREATE_TABLES_SQL)

            # Check if national_material_code column exists in canonical_materials
            cur.execute("PRAGMA table_info(canonical_materials)")
            columns = [c[1] for c in cur.fetchall()]

            if "national_material_code" not in columns:
                # Migrate canonical_materials table cleanly
                cur.execute(
                    """
                    CREATE TABLE IF NOT EXISTS canonical_materials_new (
                        id INTEGER PRIMARY KEY AUTOINCREMENT,
                        national_material_code TEXT UNIQUE NOT NULL,
                        canonical_code TEXT UNIQUE,
                        standardized_description TEXT NOT NULL,
                        canonical_description TEXT,
                        category TEXT,
                        material_type TEXT,
                        standard_specification TEXT,
                        standard_uom TEXT,
                        technical_attributes TEXT,
                        approval_status TEXT DEFAULT 'APPROVED',
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                    );
                    """
                )
                cur.execute("DROP TABLE IF EXISTS canonical_materials")
                cur.execute("ALTER TABLE canonical_materials_new RENAME TO canonical_materials")
                conn.commit()

            # Seed / Upsert the 8 default canonical prototype items
            for idx, item in enumerate(DEFAULT_PROTOTYPE_CANONICALS, start=1):
                cur.execute(
                    """
                    INSERT INTO canonical_materials (
                        national_material_code, canonical_code, standardized_description,
                        canonical_description, category, material_type,
                        standard_specification, standard_uom, technical_attributes, approval_status
                    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                    ON CONFLICT(national_material_code) DO UPDATE SET
                        canonical_code = excluded.canonical_code,
                        standardized_description = excluded.standardized_description,
                        canonical_description = excluded.canonical_description,
                        category = excluded.category,
                        material_type = excluded.material_type,
                        standard_specification = excluded.standard_specification,
                        standard_uom = excluded.standard_uom,
                        technical_attributes = excluded.technical_attributes,
                        approval_status = excluded.approval_status,
                        updated_at = CURRENT_TIMESTAMP
                    """,
                    (
                        item["national_material_code"],
                        item["canonical_code"],
                        item["standardized_description"],
                        item["standardized_description"],
                        item["category"],
                        item["material_type"],
                        item["standard_specification"],
                        item["standard_uom"],
                        json.dumps(item["technical_attributes"]),
                        item["approval_status"],
                    ),
                )

            # Ensure cross-enterprise mappings reflect NMM codes
            self._ensure_sample_mappings(cur)
            conn.commit()

    def _ensure_sample_mappings(self, cur: sqlite3.Cursor) -> None:
        """
        Seeds standard multi-enterprise mappings for ONGC and BHEL items
        to clearly demonstrate CPSE A -> Original Code, CPSE B -> Original Code.
        """
        sample_code_pairings = [
            # NMM-000001 (SS304 Hex Bolt)
            ("ONGC", "ONGC-BLT-1001", "NMM-000001", 0.94),
            ("BHEL", "BHEL-MEC-001", "NMM-000001", 0.96),
            # NMM-000002 (SS316 Hex Bolt)
            ("ONGC", "ONGC-BLT-1002", "NMM-000002", 0.93),
            ("BHEL", "BHEL-MEC-002", "NMM-000002", 0.95),
            # NMM-000003 (CS Pipe)
            ("ONGC", "ONGC-PIP-2001", "NMM-000003", 0.92),
            ("BHEL", "BHEL-PIP-001", "NMM-000003", 0.95),
            # NMM-000004 (Ball Valve)
            ("ONGC", "ONGC-VLV-3001", "NMM-000004", 0.91),
            ("BHEL", "BHEL-VLV-001", "NMM-000004", 0.94),
            # NMM-000005 (Centrifugal Pump Impeller)
            ("ONGC", "ONGC-PMP-4001", "NMM-000005", 0.90),
            ("BHEL", "BHEL-PMP-001", "NMM-000005", 0.93),
            # NMM-000006 (Transformer Oil)
            ("ONGC", "ONGC-OIL-5001", "NMM-000006", 0.89),
            # NMM-000007 (Spiral Gasket)
            ("ONGC", "ONGC-GSK-6001", "NMM-000007", 0.91),
            # NMM-000008 (Pipe Elbow)
            ("ONGC", "ONGC-ELB-7001", "NMM-000008", 0.92),
        ]

        for cpse, code, nmm_code, conf in sample_code_pairings:
            # Check if source material exists
            cur.execute(
                "SELECT id, description FROM source_materials WHERE cpse_name = ? AND material_code = ?",
                (cpse, code),
            )
            src_row = cur.fetchone()
            if not src_row:
                continue

            src_id = src_row["id"]
            src_desc = src_row["description"]

            # Fetch canonical description
            cur.execute(
                "SELECT standardized_description FROM canonical_materials WHERE national_material_code = ?",
                (nmm_code,),
            )
            can_row = cur.fetchone()
            if not can_row:
                continue
            can_desc = can_row["standardized_description"]

            # Upsert into material_mappings
            cur.execute(
                "SELECT id FROM material_mappings WHERE source_material_id = ?",
                (src_id,),
            )
            existing_map = cur.fetchone()

            if existing_map:
                cur.execute(
                    """
                    UPDATE material_mappings
                    SET canonical_material_code = ?,
                        canonical_description = ?,
                        match_status = 'APPROVED',
                        confidence = ?,
                        reviewer = 'Govt Reviewer (Demo Auditor: audit.officer@cpse.gov.in)'
                    WHERE id = ?
                    """,
                    (nmm_code, can_desc, conf, existing_map["id"]),
                )
            else:
                cur.execute(
                    """
                    INSERT INTO material_mappings (
                        source_material_id, cpse_name, original_material_code,
                        original_description, canonical_material_code, canonical_description,
                        match_status, confidence, reviewer
                    ) VALUES (?, ?, ?, ?, ?, ?, 'APPROVED', ?, 'Govt Reviewer (Demo Auditor: audit.officer@cpse.gov.in)')
                    """,
                    (src_id, cpse, code, src_desc, nmm_code, can_desc, conf),
                )

    def get_next_nmm_code(self) -> str:
        """
        Determines the next deterministic prototype NMM code:
        Queries canonical_materials, extracts the maximum numeric suffix, and adds 1.
        e.g., if max is NMM-000008 -> returns NMM-000009.
        Safe against gaps and deleted records.
        """
        with self._get_connection() as conn:
            cur = conn.cursor()
            cur.execute("SELECT national_material_code FROM canonical_materials WHERE national_material_code LIKE 'NMM-%'")
            rows = cur.fetchall()
            max_num = 0
            for r in rows:
                code_str = r[0] if isinstance(r, (list, tuple)) else r["national_material_code"]
                parts = code_str.split("-")
                if len(parts) >= 2 and parts[1].isdigit():
                    val = int(parts[1])
                    if val > max_num:
                        max_num = val
            next_num = max_num + 1
            return f"NMM-{next_num:06d}"

    def find_existing_canonical_match(
        self,
        source_text: str,
        threshold: float = 0.75,
    ) -> Optional[Dict[str, Any]]:
        """
        Checks whether an existing canonical material matches source_text closely enough
        to prevent duplicate canonical prototype creation (idempotency requirement).
        """
        from backend.app.ml.hybrid_engine import get_hybrid_engine
        engine = get_hybrid_engine()

        with self._get_connection() as conn:
            cur = conn.cursor()
            cur.execute(
                """
                SELECT id, national_material_code, canonical_code,
                       standardized_description, category, material_type,
                       standard_specification, standard_uom, approval_status
                FROM canonical_materials
                """
            )
            canonicals = [dict(r) for r in cur.fetchall()]

            best_match = None
            best_score = -1.0
            for can in canonicals:
                # Compare against standardized description
                res1 = engine.compare(source_text, can["standardized_description"])
                score = res1["hybrid_score"]
                res = res1

                # Also compare against description + spec if spec exists
                if can.get("standard_specification"):
                    res2 = engine.compare(
                        source_text,
                        f"{can['standardized_description']} {can['standard_specification']}"
                    )
                    if res2["hybrid_score"] > score:
                        score = res2["hybrid_score"]
                        res = res2

                if score > best_score:
                    best_score = score
                    if (res["match_decision"] == "MATCH" or score >= threshold) and not res["technical_tokens"]["has_conflicts"]:
                        best_match = can

            if best_match and (best_score >= threshold):
                return best_match
            return None

    def create_prototype_canonical(
        self,
        source_material: Dict[str, Any],
        performed_by: str = "AI_STANDARDIZATION_ENGINE",
        reason: Optional[str] = None,
    ) -> Dict[str, Any]:
        """
        Creates a new Prototype Common Material Code (NMM Series) for previously unseen materials:
        1. Checks whether a sufficiently similar canonical material already exists (idempotency).
        2. Generates the next deterministic NMM code (e.g. NMM-000009).
        3. Synthesizes canonical description without hallucinating technical attributes.
        4. Sets explicit prototype status: PENDING / requires validation.
        5. Persists linkage in material_mappings with match_status = 'PENDING'.
        6. Logs immutable audit trail entry: CREATE_CANONICAL_CODE.
        """
        src_desc = (source_material.get("description") or "").strip()
        if not src_desc:
            raise ValueError("Cannot create canonical material: missing source description.")

        src_text = src_desc
        if source_material.get("specification"):
            src_text += f" {source_material['specification']}"
        if source_material.get("material_grade"):
            src_text += f" {source_material['material_grade']}"

        # 1. Idempotency check: Reuse existing canonical if close match exists
        existing = self.find_existing_canonical_match(src_text, threshold=0.75)
        if existing:
            # If source_material has an id, ensure mapping exists
            src_id = source_material.get("id")
            if src_id:
                with self._get_connection() as conn:
                    cur = conn.cursor()
                    cur.execute(
                        "SELECT id FROM material_mappings WHERE source_material_id = ?",
                        (src_id,),
                    )
                    existing_map = cur.fetchone()
                    if not existing_map:
                        cur.execute(
                            """
                            INSERT INTO material_mappings (
                                source_material_id, cpse_name, original_material_code,
                                original_description, canonical_material_code, canonical_description,
                                match_status, confidence, reviewer
                            ) VALUES (?, ?, ?, ?, ?, ?, 'PENDING', 1.0, ?)
                            """,
                            (
                                src_id,
                                source_material.get("cpse_name", "CPSE"),
                                source_material.get("material_code", "N/A"),
                                src_desc,
                                existing["national_material_code"],
                                existing["standardized_description"],
                                performed_by,
                            ),
                        )
                        conn.commit()
            return existing

        # 2. Generate next deterministic NMM code
        nmm_code = self.get_next_nmm_code()

        # 3. Canonical description & category
        std_desc = generate_canonical_description(source_material)
        category = determine_canonical_category(source_material)

        # 4. Technical attributes
        from backend.app.ml.text_normalizer import extract_technical_tokens
        tech_tokens = extract_technical_tokens(src_text)
        tech_attrs = {
            "code_type": "Prototype Common Material Code",
            "status_note": "AI-generated prototype — requires validation",
            "source_reference": f"{source_material.get('cpse_name', 'CPSE')}:{source_material.get('material_code', 'N/A')}",
            "material_grade": source_material.get("material_grade") or "N/A",
            "dimensions": source_material.get("dimensions") or "N/A",
            "specification": source_material.get("specification") or "N/A",
            "extracted_tokens": list(tech_tokens),
        }

        # 5. Persist to canonical_materials
        with self._get_connection() as conn:
            cur = conn.cursor()
            cur.execute(
                """
                INSERT INTO canonical_materials (
                    national_material_code, canonical_code, standardized_description,
                    canonical_description, category, material_type,
                    standard_specification, standard_uom, technical_attributes,
                    approval_status
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 'PENDING')
                """,
                (
                    nmm_code,
                    nmm_code,
                    std_desc,
                    std_desc,
                    category,
                    source_material.get("material_type") or "AI-Generated Prototype Standard",
                    source_material.get("specification") or "Pending Standardization",
                    source_material.get("unit_of_measure") or "EA",
                    json.dumps(tech_attrs),
                ),
            )
            canonical_id = cur.lastrowid

            # 6. Persist initial mapping in material_mappings if source has an ID
            src_id = source_material.get("id")
            if src_id:
                cur.execute(
                    """
                    SELECT id FROM material_mappings WHERE source_material_id = ?
                    """,
                    (src_id,),
                )
                existing_map = cur.fetchone()
                if existing_map:
                    cur.execute(
                        """
                        UPDATE material_mappings
                        SET canonical_material_code = ?,
                            canonical_description = ?,
                            match_status = 'PENDING',
                            confidence = 1.0,
                            reviewer = ?
                        WHERE id = ?
                        """,
                        (nmm_code, std_desc, performed_by, existing_map[0]),
                    )
                else:
                    cur.execute(
                        """
                        INSERT INTO material_mappings (
                            source_material_id, cpse_name, original_material_code,
                            original_description, canonical_material_code, canonical_description,
                            match_status, confidence, reviewer
                        ) VALUES (?, ?, ?, ?, ?, ?, 'PENDING', 1.0, ?)
                        """,
                        (
                            src_id,
                            source_material.get("cpse_name", "CPSE"),
                            source_material.get("material_code", "N/A"),
                            src_desc,
                            nmm_code,
                            std_desc,
                            performed_by,
                        ),
                    )
            conn.commit()

        # 7. Record immutable audit log
        from backend.app.cpse.audit_service import get_audit_service
        audit_svc = get_audit_service()
        audit_reason = reason or "Created prototype canonical material because no suitable existing canonical material met the configured matching threshold."
        audit_svc.record_log(
            action="CREATE_CANONICAL_CODE",
            entity_type="canonical_materials",
            entity_id=nmm_code,
            old_value=None,
            new_value=json.dumps({
                "national_material_code": nmm_code,
                "standardized_description": std_desc,
                "category": category,
                "approval_status": "PENDING",
                "status_note": "AI-generated prototype — requires validation",
                "source_material_id": src_id,
                "source_cpse": source_material.get("cpse_name"),
                "source_code": source_material.get("material_code"),
            }),
            performed_by=performed_by,
            reason=audit_reason,
            details={
                "code": nmm_code,
                "description": std_desc,
                "category": category,
                "source_material_id": src_id,
            },
        )

        return {
            "id": canonical_id,
            "national_material_code": nmm_code,
            "canonical_code": nmm_code,
            "standardized_description": std_desc,
            "category": category,
            "material_type": source_material.get("material_type") or "AI-Generated Prototype Standard",
            "approval_status": "PENDING",
            "code_type_label": "Prototype Common Material Code",
            "status_note": "AI-generated prototype — requires validation",
            "source_reference": f"{source_material.get('cpse_name', 'CPSE')}:{source_material.get('material_code', 'N/A')}",
        }

    def get_canonical_materials(
        self,
        search: Optional[str] = None,
        category: Optional[str] = None,
        approval_status: Optional[str] = None,
        cpse_name: Optional[str] = None,
        page: int = 1,
        page_size: int = 20,
    ) -> Dict[str, Any]:
        """
        GET /api/canonical-materials
        Retrieves paginated list of canonical materials with mapped CPSEs,
        original codes count/summary, confidence, and approval status.
        """
        page = max(1, page)
        page_size = max(1, min(100, page_size))
        offset = (page - 1) * page_size

        conditions = []
        params = []

        if search and search.strip():
            s = f"%{search.strip().lower()}%"
            conditions.append(
                """(
                    LOWER(c.national_material_code) LIKE ?
                    OR LOWER(c.standardized_description) LIKE ?
                    OR LOWER(c.category) LIKE ?
                    OR LOWER(c.standard_specification) LIKE ?
                    OR LOWER(c.technical_attributes) LIKE ?
                )"""
            )
            params.extend([s, s, s, s, s])

        if category and category.strip() and category.upper() != "ALL":
            conditions.append("c.category = ?")
            params.append(category.strip())

        if approval_status and approval_status.strip() and approval_status.upper() != "ALL":
            conditions.append("c.approval_status = ?")
            params.append(approval_status.strip().upper())

        where_clause = f"WHERE {' AND '.join(conditions)}" if conditions else ""

        with self._get_connection() as conn:
            cur = conn.cursor()

            # Distinct categories list for dropdown filter
            cur.execute("SELECT DISTINCT category FROM canonical_materials WHERE category IS NOT NULL ORDER BY category")
            categories = [r[0] for r in cur.fetchall()]

            # Total matching records count
            cur.execute(f"SELECT COUNT(*) FROM canonical_materials c {where_clause}", params)
            total = cur.fetchone()[0]

            # Fetch paginated items
            query = f"""
                SELECT
                    c.id, c.national_material_code, c.canonical_code,
                    c.standardized_description, c.category, c.material_type,
                    c.standard_specification, c.standard_uom, c.technical_attributes,
                    c.approval_status, c.created_at, c.updated_at
                FROM canonical_materials c
                {where_clause}
                ORDER BY c.national_material_code ASC
                LIMIT ? OFFSET ?
            """
            cur.execute(query, params + [page_size, offset])
            rows = cur.fetchall()

            items = []
            for row in rows:
                nmm_code = row["national_material_code"]

                # Fetch mapped CPSEs and original codes from material_mappings
                cur.execute(
                    """
                    SELECT
                        m.id as mapping_id, m.cpse_name, m.original_material_code,
                        m.original_description, m.match_status, m.confidence,
                        m.reviewer, m.timestamp,
                        s.specification, s.unit_of_measure, s.material_grade
                    FROM material_mappings m
                    LEFT JOIN source_materials s ON m.source_material_id = s.id
                    WHERE m.canonical_material_code = ?
                    ORDER BY m.cpse_name ASC
                    """,
                    (nmm_code,),
                )
                map_rows = cur.fetchall()

                # Filter by cpse_name if requested
                if cpse_name and cpse_name.strip() and cpse_name.upper() != "ALL":
                    if not any(r["cpse_name"] == cpse_name.strip() for r in map_rows):
                        continue

                mapped_cpses = sorted(list(set(r["cpse_name"] for r in map_rows)))
                original_codes = [r["original_material_code"] for r in map_rows]

                # Calculate confidence
                confidences = [r["confidence"] for r in map_rows if r["confidence"] is not None]
                avg_confidence = round(sum(confidences) / len(confidences), 4) if confidences else 0.90

                # Parse technical attributes
                try:
                    tech_attrs = json.loads(row["technical_attributes"]) if row["technical_attributes"] else {}
                except Exception:
                    tech_attrs = {}

                # Build cpse_mappings list
                cpse_mappings = []
                for m in map_rows:
                    cpse_mappings.append(
                        {
                            "mapping_id": m["mapping_id"],
                            "cpse_name": m["cpse_name"],
                            "original_material_code": m["original_material_code"],
                            "original_description": m["original_description"],
                            "specification": m["specification"] or "N/A",
                            "unit_of_measure": m["unit_of_measure"] or "N/A",
                            "material_grade": m["material_grade"] or "N/A",
                            "match_status": m["match_status"],
                            "confidence": m["confidence"],
                            "reviewer": m["reviewer"],
                            "timestamp": m["timestamp"],
                        }
                    )

                items.append(
                    {
                        "id": row["id"],
                        "national_material_code": nmm_code,
                        "code_type_label": "Prototype Common Material Code",
                        "standardized_description": row["standardized_description"],
                        "category": row["category"] or "General Equipment",
                        "material_type": row["material_type"] or "Standard Material",
                        "standard_specification": row["standard_specification"] or "National Standard Specification",
                        "standard_uom": row["standard_uom"] or "EA",
                        "technical_attributes": tech_attrs,
                        "approval_status": row["approval_status"] or "APPROVED",
                        "source_materials_count": len(map_rows),
                        "mapped_cpses": mapped_cpses,
                        "original_codes": original_codes,
                        "cpse_mappings": cpse_mappings,
                        "confidence": avg_confidence,
                        "created_at": row["created_at"],
                        "updated_at": row["updated_at"] or row["created_at"],
                    }
                )

        total_pages = (total + page_size - 1) // page_size if total > 0 else 1

        return {
            "total": total,
            "page": page,
            "page_size": page_size,
            "total_pages": total_pages,
            "categories": categories,
            "code_type": "Prototype Common Material Code",
            "disclaimer": PROTOTYPE_DISCLAIMER,
            "items": items,
        }

    def get_canonical_material_detail(self, identifier: str) -> Dict[str, Any]:
        """
        GET /api/canonical-materials/{id}
        Retrieves complete detailed record with multi-branch provenance tree:
        Common Code (NMM-000001)
        ↓
        Canonical Description
        ↓
        CPSE A → Original Code
        CPSE B → Original Code
        CPSE C → Original Code
        """
        ident = str(identifier).strip()

        with self._get_connection() as conn:
            cur = conn.cursor()

            # Search by ID or national_material_code or canonical_code
            if ident.isdigit():
                cur.execute(
                    """
                    SELECT id, national_material_code, canonical_code,
                           standardized_description, category, material_type,
                           standard_specification, standard_uom, technical_attributes,
                           approval_status, created_at, updated_at
                    FROM canonical_materials
                    WHERE id = ? OR national_material_code = ?
                    """,
                    (int(ident), f"NMM-{int(ident):06d}"),
                )
            else:
                cur.execute(
                    """
                    SELECT id, national_material_code, canonical_code,
                           standardized_description, category, material_type,
                           standard_specification, standard_uom, technical_attributes,
                           approval_status, created_at, updated_at
                    FROM canonical_materials
                    WHERE LOWER(national_material_code) = ? OR LOWER(canonical_code) = ?
                    """,
                    (ident.lower(), ident.lower()),
                )

            row = cur.fetchone()
            if not row:
                raise ValueError(f"Canonical material with identifier '{identifier}' not found.")

            nmm_code = row["national_material_code"]

            # Parse technical attributes
            try:
                tech_attrs = json.loads(row["technical_attributes"]) if row["technical_attributes"] else {}
            except Exception:
                tech_attrs = {}

            # Fetch mapped source materials with complete details
            cur.execute(
                """
                SELECT
                    m.id as mapping_id, m.cpse_name, m.original_material_code,
                    m.original_description, m.match_status, m.confidence,
                    m.reviewer, m.timestamp,
                    s.id as source_id, s.specification, s.unit_of_measure,
                    s.material_grade, s.dimensions, s.manufacturer,
                    s.part_number, s.source_file, s.created_at as ingested_at
                FROM material_mappings m
                LEFT JOIN source_materials s ON m.source_material_id = s.id
                WHERE m.canonical_material_code = ?
                ORDER BY m.cpse_name ASC, m.original_material_code ASC
                """,
                (nmm_code,),
            )
            map_rows = cur.fetchall()

            source_materials = []
            cpse_mappings = []
            traceability_branches = []

            for r in map_rows:
                src_item = {
                    "source_material_id": r["source_id"],
                    "cpse_name": r["cpse_name"],
                    "material_code": r["original_material_code"],
                    "description": r["original_description"],
                    "specification": r["specification"] or "N/A",
                    "unit_of_measure": r["unit_of_measure"] or "N/A",
                    "material_grade": r["material_grade"] or "N/A",
                    "dimensions": r["dimensions"] or "N/A",
                    "manufacturer": r["manufacturer"] or "N/A",
                    "part_number": r["part_number"] or "N/A",
                    "source_file": r["source_file"] or "N/A",
                    "ingested_at": r["ingested_at"],
                }
                source_materials.append(src_item)

                mapping_item = {
                    "mapping_id": r["mapping_id"],
                    "cpse_name": r["cpse_name"],
                    "original_material_code": r["original_material_code"],
                    "original_description": r["original_description"],
                    "match_status": r["match_status"],
                    "confidence": r["confidence"],
                    "reviewer": r["reviewer"],
                    "timestamp": r["timestamp"],
                }
                cpse_mappings.append(mapping_item)

                # Traceability Tree Branch
                traceability_branches.append(
                    {
                        "cpse_name": r["cpse_name"],
                        "original_code": r["original_material_code"],
                        "original_description": r["original_description"],
                        "specification": r["specification"] or "N/A",
                        "unit_of_measure": r["unit_of_measure"] or "N/A",
                        "material_grade": r["material_grade"] or "N/A",
                        "dimensions": r["dimensions"] or "N/A",
                        "match_status": r["match_status"],
                        "confidence": r["confidence"],
                        "reviewer": r["reviewer"],
                        "timestamp": r["timestamp"],
                    }
                )

            # Average confidence
            confidences = [r["confidence"] for r in map_rows if r["confidence"] is not None]
            avg_confidence = round(sum(confidences) / len(confidences), 4) if confidences else 0.90

            # Traceability tree structure requested by user
            traceability_tree = {
                "common_code": nmm_code,
                "code_type": "Prototype Common Material Code",
                "canonical_description": row["standardized_description"],
                "category": row["category"],
                "material_type": row["material_type"],
                "standard_specification": row["standard_specification"],
                "standard_uom": row["standard_uom"],
                "approval_status": row["approval_status"],
                "branches": traceability_branches,
            }

            return {
                "id": row["id"],
                "national_material_code": nmm_code,
                "code_type_label": "Prototype Common Material Code",
                "standardized_description": row["standardized_description"],
                "category": row["category"] or "General Equipment",
                "material_type": row["material_type"] or "Standard Material",
                "standard_specification": row["standard_specification"] or "National Standard Specification",
                "standard_uom": row["standard_uom"] or "EA",
                "technical_attributes": tech_attrs,
                "approval_status": row["approval_status"] or "APPROVED",
                "confidence": avg_confidence,
                "source_materials": source_materials,
                "cpse_mappings": cpse_mappings,
                "traceability_tree": traceability_tree,
                "created_at": row["created_at"],
                "updated_at": row["updated_at"] or row["created_at"],
                "disclaimer": PROTOTYPE_DISCLAIMER,
            }


# Singleton instance
_canonical_service: Optional[CanonicalMaterialService] = None


def get_canonical_service() -> CanonicalMaterialService:
    global _canonical_service
    if _canonical_service is None:
        _canonical_service = CanonicalMaterialService()
    return _canonical_service
